### ISSUE TITLE
Powered Quarry works only with fuel like fueled quarry.

### ISSUE THREAD

**Issue by Knito58** [APengu/SimpleQuarry#1]
MC 1.12
Forge 14.21.1.2443
Simple Quarry 1.0.7
Gamemode SSP

After a lot of pain finally the powered quarry is accomplished. I go to the mining world and wire it up with xnet. Now why doesn't it accept this good, fresh RF which is provided by my trusty RFTools Coal Generator? Is xnet to be blamed? The GUI has a long vertical bar which I supposed to be there for showing the RF-Fill-Status. No. When hovering the mouse over it it says "0/1 block to break". Nearby, like in the fueled quarry is a little slot which accepts coal and then the quarry runs.

OK. This would be "powered" if it would accept at least coal from a hopper. The fueled quarry doesn't. Maybe this one? Then I could automate it with xnet. 

But No. Quarry says: "Noh!" (Cough!)

Is there something to be done beside wiring it up and feeding it coal to have it work?

Greetings, Konitor

**Comment by APengu** [comment]
are you providing 200 RF/t? If not, there's your problem.

**Comment by Knito58** [comment]
Thank you! Coal Gen does only 60 RF / Tick. Will put 3 more to it.

**Comment by APengu** [comment]
Read description more carefuly next time ;)
![image](https://user-images.githubusercontent.com/10291214/28994995-8b36afaa-79e5-11e7-87e5-5e0a1a5b950f.png)

**Comment by Knito58** [comment]
Yes sir!
