### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by arcriley** [APengu/SimpleQuarry#2]
Your mod cannot be legally used without a license.

Github's https://choosealicense.com/ makes it easy.

**Comment by APengu** [comment]
Okay, done ;)

**Comment by arcriley** [comment]
Unless you forget to push, this isn't resolved yet.

The software license is usually a file in the project root called LICENSE or COPYING. Since copyright is automatic and defaults to all rights reserved, without this your mod cannot be used or distributed without your express permission.
