### ISSUE TITLE
Powered Quarry consumes maximum available energy.  Wastes most of it.

### ISSUE THREAD

**Issue by CplPibald** [APengu/SimpleQuarry#4]
Connect a high-energy-output connector to a powered quarry.  I used a draconic energy relay crystal (max transfer 4MRF/t) backed by a 1.5GRF storage.  Quarry will consume energy at the maximum rate the energy supplier can output, in this case rapidly draining the entire storage.  The quarry then uses 200RF/t to run, and discards the remainder.

The input value of `IEnergyStorage.receiveEnergy()` is the maximum available energy, and the return value is supposed to be the amount of energy actually consumed.  However, In [`TilePoweredQuarry.receiveEnergy()`](https://github.com/APengu/SimpleQuarry/blob/777d4b234e1e2cdd61df5a54e3dd9464d6d7fdf7/src/main/java/com/endie/simplequarry/tile/TilePoweredQuarry.java#L198), the maximum value is always returned, resulting in that value being drained from the energy source every tick.

To fix, return the actual used power (`200 * storage.consumeQF()`) instead of `maxReceive` from this function.

```
@Override
	public int receiveEnergy(int maxReceive, boolean simulate)
	{
		if(maxReceive >= 200)
			return 200 * storage.consumeQF(null, maxReceive / 200, simulate);
		return 0;
}
```

**Comment by APengu** [comment]
It's intended. Use flux gates from draconic, or really anything that can limit the amount of RF to 200/tick

**Comment by CplPibald** [comment]
Any chance of gating this behavior behind a configuration setting?  This is the only Forge Energy consumer I've ever seen that behaves this way (which is why I thought it was a bug).  I'm worried that if I unban powered quarries on my server, it will cause players to be confused and angry.
